version: "3.9"
services:
  db:
    image: postgres:15
    container_name: reservations_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-reservations}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: reservations_backend
    env_file: ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    command: npm run start:dev
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: reservations_frontend
    env_file: ./frontend/.env.local
    depends_on:
      - backend
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:
